name: MOnuorah Github Actions Notification
on: push
jobs:
  runs-on: ubuntu-latest
  env: 
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  steps:
    - name: slack notification
    - uses: actions/checkout@v2
    - uses: rtCamp/action-slack-notify@v2
      with: 
        status: ${{ job.status }}
        channel: '#task-review'
