name: JavaScript Tasks - CI/CD
on: push
on: 
  schedule:
    - cron: "0 0 * * *"
jobs: 
  Test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: echo "This job automatically triggered by ${{ github.event_name }} event"
      - run: npm start

  messageSlack: 
    runs-on: ubuntu-latest
    steps:
    - name: Notification Slack
      uses: rtCamp/action-slack-notify@v2
      env: 
        SLACK_CHANNEL: task-review
        SLACK_TITLE: MOnuorah-CI
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        Status: ${{ job.status }} 